# Generated by Django 5.2.5 on 2025-09-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='party',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='name',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/'),
        ),
        migrations.AddField(
            model_name='position',
            name='maximumvote',
            field=models.IntegerField(default=1),
        ),
    ]
