# Generated by Django 5.2.5 on 2025-09-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_app', '0002_rename_name_candidate_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
                ('votersid', models.BigIntegerField(unique=True)),
            ],
        ),
    ]
