# Generated by Django 5.2.5 on 2025-09-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_app', '0005_vote_created_at_vote_position_alter_candidate_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='votersid',
        ),
        migrations.AddField(
            model_name='voter',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='voter_images/'),
        ),
        migrations.AddField(
            model_name='voter',
            name='voterid',
            field=models.CharField(default='TEMP-ID', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
